title: My Portfolio
author: Terryann
email: your-email@domain.com
description: This page is dedicated to web development projects

# social links
twitter_username: not applicable
github_username:  DTSDPGP

show_excerpts: true # set to false to remove excerpts on the homepage
